name: CI Checks

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-build:
    name: Lint, Build, and Conflict Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze

      - name: Build Flutter Web
        run: flutter build web